spring.application.name=spikenews

# Configuração da Base de Dados SQLite
spring.datasource.url=jdbc:sqlite:spike_news.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Pool de Conexões (HikariCP) e Habilitação de Foreign Keys no SQLite
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys = ON;

# Configurações do JPA / Hibernate 6
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.foreign_keys=true

# Configuração de Segurança e JWT
api.security.token.secret=${JWT_SECRET:spike-news-secret-key-development-jwt-token-2026-auth}
api.security.token.expiration-hours=24

